lidar_bridge:
  ros__parameters:
    qos_overrides:
      /pcd_lidar:
        publisher:
          reliability: best_effort
          durability: volatile
          history: keep_last
          depth: 5